---
title: "BinMat: for fragment analysis data"
author: "Clarke van Steenderen"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{BinMat}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

*Department of Zoology and Entomology*

*The Centre for Biological Control* (https://www.ru.ac.za/centreforbiologicalcontrol/)

*Rhodes University, Grahamstown, Eastern Cape, South Africa*

*e-mail:* vsteenderen@gmail.com

<br/><br/>

The idea behind this package was taken from Clarke's M.Sc. thesis entitled "*A genetic analysis of the species and intraspecific lineages of* Dactylopius *Costa (Hemiptera:Dactylopiidae)*" (doi = [10.13140/RG.2.2.28470.86083](https://www.researchgate.net/publication/339124038_A_genetic_analysis_of_the_species_and_intraspecific_lineages_of_Dactylopius_Costa_Hemiptera_Dactylopiidae)). The GUI version of this package is available on the [R Shiny online server](https://clarkevansteenderen.shinyapps.io/BINMAT/), or it is accessible via GitHub by typing: shiny::runGitHub("BinMat", "CJMvS") into the console in R.

<br/>

---

**OVERVIEW**

This program was written to rapidly consolidate binary matrices derived from dominant marker genetic analyses (such as for inter-simple sequence repeats (ISSRs) and amplified fragment length polymorphisms (AFLPs)). 
This is applied to data consisting of replicate pairs.
The user is able to obtain summary statistics, generate non-metric multidimensional scaling (nMDS) plots, hierarchical clustering trees using the UPGMA method, and filter their data according to a specified minimum peak number threshold.

---

**UPLOADING DATA**

Binary data containing replicate pairs that need be consolidated should be in the following example format, saved as a .csv file:

|                      		| 	Locus 1     	  | Locus 2   			| Locus 3   		| Locus 4 	    	| Locus 5 	    	|
|----------------------		|:------------:	      | :------------:	    |:------------:	    |:------------:	    |:------------:	    |
| Sample A replicate 1 		| 	0       	      |  	0       	    | 	1       	    | 	1       	    | 	1       	    |
| Sample A replicate 2 		| 	0       	      |  	0       	    | 	1       	    | 	1       	    | 	1       	    |
| Sample B replicate 1 		| 	1       	      |  	1       	    | 	0       	    | 	0       	    | 	0       	    |
| Sample B replicate 2 		| 	0       	      |  	1       	    | 	0       	    | 	0       	    | 	1       	    |


Note that replicate pairs must be directly underneath each other, and that each sample needs to have a unique name.

The following conditions are applied to binary data replicates:
 1. A 0 and a 1 produces a "?"
 2. A 0 and a 0 produces a "0"
 3. A 1 and a 1 produces a "1"    
 
The consolidated output for the above example would thus be:

Sample A: 0 0 1 1 1

Sample B: ? 1 0 0 ?

---

Binary data that has already been consolidated can have grouping information in the second column, as shown in the example below. This matrix can be used to create an nMDS plot coloured by group.


|           |    Group        	| 	Locus 1     	  | Locus 2   			| Locus 3   		| Locus 4 	    	| Locus 5 	    	|
|-----------|:----------:		|:------------:	      | :------------:	    |:------------:	    |:------------:	    |:------------:	    |
| Sample A  |    Africa	    	| 	?       	      |  	0       	    | 	1       	    | 	1       	    | 	1       	    |
| Sample B  |    Asia	    	| 	0       	      |  	0       	    | 	1       	    | 	1       	    | 	?       	    |
| Sample C  |    Europe	    	| 	1       	      |  	?       	    | 	0       	    | 	0       	    | 	0       	    |
| Sample D  |    USA	        | 	?       	      |  	1       	    | 	0       	    | 	?       	    | 	1       	    |
                            

---

   
**METHODS**

Mismatch/Euclidean error = (f01 + f10) / (f01 + f10 + f00 + f11)

The Euclidean error rate includes the shared absence of a band (f00).

Jaccard error = (f01 + f10) / (f01 + f10 + f11)

<br/>

The Jaccard error rate does not take shared absences of bands into account. The error rate will thus be inflated compared to the Euclidean.

In the formulae above, 'f' refers to the frequency of each combination (i.e. 'f01 + f10' means the sum of all the occurences of a zero and a one, and a one and a zero).
An error value is calculated for each replicate pair, and an average obtained representing the whole dataset. 

The error rates for the example samples below would be:

<br/>

**Sample X rep 1: 0 1 1 0**

**Sample X rep 2: 1 0 1 0**

<br/>

Euclidean error = (1+1) / (1+1+1+1) = 2/4 = 0.5

Jaccard error = (1+1) / (1+1+1) = 2/3 = 0.67

<br/>

**Sample Y rep 1: 1 1 1 0**

**Sample Y rep 2: 1 1 0 0**

<br/>

Euclidean error = (1) / (1+1+2) = 1/4 = 0.25

Jaccard error = (1) / (1+2) = 1/3 = 0.33

---

Average Euclidean error = (0.5+0.25) / 2 = 0.38

Average Jaccard error = (0.67+0.33) / 2 = 0.5

---

**WORKED EXAMPLE**

```{r setup}
library(BinMat)
```
